name: 天翼云盘签到

on:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * *'
      timezone: 'Asia/Shanghai'

jobs:
  sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests rsa

      - name: Run script
        env:
          ty_username: ${{ secrets.TY_USERNAME }}
          ty_password: ${{ secrets.TY_PASSWORD }}
          WXPUSHER_APP_TOKEN: ${{ secrets.WXPUSHER_APP_TOKEN }}
          WXPUSHER_UID: ${{ secrets.WXPUSHER_UID }}
        run: python tianyiyun.py
